---
ID: "b6e8084a-e0e2-4b2e-bbb9-11222edf6b35"
Parent: "57f2e85d-d695-4e6c-8c89-947ce5443e2e"
Template: "1226c3c7-2d1f-48f5-87b4-c1da459f05e5"
Path: /sitecore/content/Verticals/Services/Home/services
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{E9B6C600-C6E8-4867-BCB7-8B0DC5F19840}"
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 150
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Value: |
    <r xmlns:p="p" xmlns:s="s"
      p:p="1">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
        <r
          uid="{675AB9F2-78B7-4930-A866-A6017F070235}"
          p:before="*"
          s:ds="local:/Data/Heading CTA 1"
          s:id="{89E1D547-7CD6-4EF0-9A27-1E99410797DD}"
          s:par="GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;FieldNames=%7BB51C9BF5-3DC7-48A9-8B7A-EB1890FD95E6%7D&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=1"
          s:ph="headless-main" />
        <r
          uid="{6ED006C2-BE02-4792-9B3C-3C5A0B76EE97}"
          p:after="r[@uid='{675AB9F2-78B7-4930-A866-A6017F070235}']"
          s:id="{7A1D9A21-B8D7-42F9-9B0B-92ABF8D1974F}"
          s:par="GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;FieldNames&amp;BackgroundImage&amp;Styles=%7C%7B2BBF52B7-A2C0-466F-9D7A-35B4CE3C79C1%7D%7C%7B7EBB6C9F-C1B0-4FB3-9B52-AEEC8055D6F4%7D%7C%7BE86E740F-58D7-4151-9977-84B0382C458F%7D&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=2"
          s:ph="headless-main" />
        <r
          uid="{80E017F4-83EE-4836-9336-A8243B6E2DC1}"
          p:after="r[@uid='{6ED006C2-BE02-4792-9B3C-3C5A0B76EE97}']"
          s:ds="local:/Data/Accordion 1"
          s:id="{5816F979-C8BB-46E9-8EC8-513C6CAF41E6}"
          s:par="GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;FieldNames&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=11"
          s:ph="headless-main" />
        <r
          uid="{4A73CE44-54B0-4FBC-A1AA-C3786C1AD19E}"
          p:after="r[@uid='{80E017F4-83EE-4836-9336-A8243B6E2DC1}']"
          s:id="{7A1D9A21-B8D7-42F9-9B0B-92ABF8D1974F}"
          s:par="GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;FieldNames&amp;BackgroundImage&amp;Styles=%7C%7B2BBF52B7-A2C0-466F-9D7A-35B4CE3C79C1%7D%7C%7B7EBB6C9F-C1B0-4FB3-9B52-AEEC8055D6F4%7D%7C%7BE86E740F-58D7-4151-9977-84B0382C458F%7D&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=7"
          s:ph="headless-main" />
        <r
          uid="{EAA5C31A-5A55-4DFC-8843-ADCBF934E1B2}"
          p:after="r[@uid='{4A73CE44-54B0-4FBC-A1AA-C3786C1AD19E}']"
          s:ds="3a7dc4f0-472c-4c73-b428-a3155c8853f2"
          s:id="{488B8AC0-0EF9-4F6F-8711-78BA182B2C4C}"
          s:par="GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;FieldNames=%7B5976CD6A-9C09-428B-AE34-83DE5144C859%7D&amp;Styles=%7C%7BBA83D200-B0FE-46C0-A5C7-E5C369D2BDA9%7D%7C%7BF50EB4F2-6C9A-4226-828C-C0F21D66F789%7D&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=6"
          s:ph="headless-main" />
        <r
          uid="{390661DE-50B8-487F-A65A-F954CF8982A9}"
          p:after="r[@uid='{EAA5C31A-5A55-4DFC-8843-ADCBF934E1B2}']"
          s:id="{15CABDFF-FFD9-48F4-826D-A4C3D7868D3A}"
          s:par="ColumnWidth1=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D%7C%7B81225C08-5783-4BED-A86A-AB2B87198885%7D&amp;ColumnWidth2=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D%7C%7B81225C08-5783-4BED-A86A-AB2B87198885%7D&amp;ColumnWidth3&amp;ColumnWidth4&amp;ColumnWidth5&amp;ColumnWidth6&amp;ColumnWidth7&amp;ColumnWidth8&amp;GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;SplitterSize=2&amp;EnabledPlaceholders=1%2C2&amp;FieldNames&amp;Styles1&amp;Styles2&amp;Styles3&amp;Styles4&amp;Styles5&amp;Styles6&amp;Styles7&amp;Styles&amp;Styles8&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=3"
          s:ph="/headless-main/container-2" />
        <r
          uid="{BBD28AEA-22EE-40B9-96BC-6A4253129F55}"
          p:after="r[@uid='{390661DE-50B8-487F-A65A-F954CF8982A9}']"
          s:ds="local:/Data/Text 1"
          s:id="{9C6D53E3-FE57-4638-AF7B-6D68304C7A94}"
          s:par="GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;FieldNames=%7BAC2C499C-3D24-4AE9-B436-811F89D71989%7D&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=4"
          s:ph="/headless-main/container-2/column-1-3" />
        <r
          uid="{FB2F9E53-1E45-4292-BA4F-3C1D33FEA1B4}"
          p:after="r[@uid='{BBD28AEA-22EE-40B9-96BC-6A4253129F55}']"
          s:ds="local:/Data/Text 2"
          s:id="{9C6D53E3-FE57-4638-AF7B-6D68304C7A94}"
          s:par="GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;FieldNames=%7BAC2C499C-3D24-4AE9-B436-811F89D71989%7D&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=5"
          s:ph="/headless-main/container-2/column-2-3" />
        <r
          uid="{0983ECCA-BCC4-40EC-8B51-85CADAC6F315}"
          p:after="r[@uid='{FB2F9E53-1E45-4292-BA4F-3C1D33FEA1B4}']"
          s:id="{15CABDFF-FFD9-48F4-826D-A4C3D7868D3A}"
          s:par="ColumnWidth1=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D%7C%7B81225C08-5783-4BED-A86A-AB2B87198885%7D&amp;ColumnWidth2=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D%7C%7B81225C08-5783-4BED-A86A-AB2B87198885%7D&amp;ColumnWidth3&amp;ColumnWidth4&amp;ColumnWidth5&amp;ColumnWidth6&amp;ColumnWidth7&amp;ColumnWidth8&amp;GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;SplitterSize=2&amp;EnabledPlaceholders=1%2C2&amp;FieldNames&amp;Styles1&amp;Styles2&amp;Styles3&amp;Styles4&amp;Styles5&amp;Styles6&amp;Styles7&amp;Styles&amp;Styles8&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=8"
          s:ph="/headless-main/container-7" />
        <r
          uid="{F927F4DF-8ABA-45D4-AF32-28C60F037090}"
          p:after="r[@uid='{0983ECCA-BCC4-40EC-8B51-85CADAC6F315}']"
          s:ds="local:/Data/Heading CTA 2"
          s:id="{89E1D547-7CD6-4EF0-9A27-1E99410797DD}"
          s:par="GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;FieldNames=%7B8D4C244D-8584-45C8-B65D-DF3343A56A7D%7D&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=9"
          s:ph="/headless-main/container-7/column-1-8" />
        <r
          uid="{4987B227-BA03-4DF4-8B3F-FEEB9A1EB03B}"
          p:after="*[1=2]"
          s:ds="local:/Data/Text 3"
          s:id="{9C6D53E3-FE57-4638-AF7B-6D68304C7A94}"
          s:par="GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;FieldNames=%7BAC2C499C-3D24-4AE9-B436-811F89D71989%7D&amp;Styles=%7C%7BE8F08B14-1ADA-4DB6-A1C3-B4177268ABCD%7D&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=10"
          s:ph="/headless-main/container-7/column-2-8" />
      </d>
    </r>
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Services
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: 
    - ID: "247be607-394a-4bf2-8c8a-509b07025dd9"
      Hint: Title
      Value: Services
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{171CCFD4-8543-428E-9A9B-8E6557E63B6D}"
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Services
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "2ffc9e8b-c8f0-4b9e-ae96-4b4634aa33c5"
